### ISSUE TITLE
Safari compatibility

### ISSUE THREAD

**Issue by Brog33** [KervynH/Focused-YouTube#1]
The script would not work in Safari with the userscript extension, but with these changes it works:

- Removed the GM.addStyle dependency
- Added custom addStyle function
- Changed run-at to document-start

[update.js.zip](https://github.com/user-attachments/files/18012030/update.js.zip)

**Comment by KervynH** [comment]
> The script would not work in Safari with the userscript extension, but with these changes it works:
> 
> * Removed the GM.addStyle dependency
> * Added custom addStyle function
> * Changed run-at to document-start
> 
> [update.js.zip](https://github.com/user-attachments/files/18012030/update.js.zip)

Thanks for pointing this out! A custom addStyle function is indeed much more robust.
